// 將已解析 tokens 產生 Android Jetpack Compose (Kotlin) 檔案字串

const toCamel = (s) => s.replace(/[-_]+([a-zA-Z0-9])/g, (_, c) => (c || '').toUpperCase()).replace(/^([A-Z])/, (m) => m.toLowerCase());
const toPascal = (s) => {
  const camel = toCamel(s);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
};

const sanitizeName = (cssVarKey) => cssVarKey.replace(/^([a-zA-Z]+-)/, '').replace(/[^a-zA-Z0-9-_]/g, '');

const hexToArgbInts = (hex) => {
  let v = hex.replace('#', '').trim();
  if (v.length === 3) {
    v = v.split('').map((c) => c + c).join('');
  }
  const r = parseInt(v.substring(0, 2), 16);
  const g = parseInt(v.substring(2, 4), 16);
  const b = parseInt(v.substring(4, 6), 16);
  return { a: 255, r, g, b };
};

export const generateAndroidCompose = ({ tokens }) => {
  if (!Array.isArray(tokens)) return '';

  const colors = tokens.filter(t => t.type === 'color');
  const dims = tokens.filter(t => t.type === 'size_px' || t.type === 'size_rem' || t.type === 'number');

  const VAR_REF = /^var\((--[A-Za-z0-9-_]+)\)$/;

  const toName = (key) => toCamel(sanitizeName(key));

  // 顏色：基底與別名（維持「繼承」語意）
  const baseColors = colors.filter(t => !VAR_REF.test(t.raw));
  const aliasColors = colors.filter(t => VAR_REF.test(t.raw));

  const colorLines = [];
  baseColors.forEach(t => {
    const name = toName(t.key);
    const { r, g, b } = hexToArgbInts(t.resolved);
    colorLines.push(`    val ${name} = Color(red = ${r}, green = ${g}, blue = ${b})`);
  });
  aliasColors.forEach(t => {
    const name = toName(t.key);
    const refKey = t.raw.match(VAR_REF)[1].replace(/^--/, '');
    const refName = toName(refKey);
    colorLines.push(`    val ${name} = ${refName}`);
  });

  // 尺寸：同樣先輸出基底，再輸出別名
  const baseDims = dims.filter(t => !VAR_REF.test(t.raw));
  const aliasDims = dims.filter(t => VAR_REF.test(t.raw));

  const dimenLines = [];
  baseDims.forEach(t => {
    const name = toName(t.key);
    if (t.type === 'size_px') {
      const v = parseFloat(t.resolved);
      dimenLines.push(`    val ${name} = ${v}.dp`);
    } else if (t.type === 'size_rem') {
      const rem = parseFloat(t.resolved);
      const sp = rem * 16; // 1rem = 16sp 預設
      dimenLines.push(`    val ${name} = ${sp}.sp`);
    } else {
      dimenLines.push(`    val ${name} = ${Number(t.resolved)}f`);
    }
  });
  aliasDims.forEach(t => {
    const name = toName(t.key);
    const refKey = t.raw.match(VAR_REF)[1].replace(/^--/, '');
    const refName = toName(refKey);
    dimenLines.push(`    val ${name} = ${refName}`);
  });

  const file = `// Generated by Variables Compile Tool
package com.example.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object DesignTokens {
${colorLines.join('\n')}

${dimenLines.join('\n')}
}
`;
  return file;
};


