// 將已解析 tokens 產生 Android Jetpack Compose (Kotlin) 檔案字串

const toCamel = (s) => s.replace(/[-_]+([a-zA-Z0-9])/g, (_, c) => (c || '').toUpperCase()).replace(/^([A-Z])/, (m) => m.toLowerCase());
const toPascal = (s) => {
  const camel = toCamel(s);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
};

const sanitizeName = (cssVarKey) => cssVarKey.replace(/^([a-zA-Z]+-)/, '').replace(/[^a-zA-Z0-9-_]/g, '');

const hexToArgbInts = (hex) => {
  let v = hex.replace('#', '').trim();
  if (v.length === 3) {
    v = v.split('').map((c) => c + c).join('');
  }
  const r = parseInt(v.substring(0, 2), 16);
  const g = parseInt(v.substring(2, 4), 16);
  const b = parseInt(v.substring(4, 6), 16);
  return { a: 255, r, g, b };
};

export const generateAndroidCompose = ({ tokens }) => {
  if (!Array.isArray(tokens)) return '';

  const colors = tokens.filter(t => t.type === 'color');
  const dims = tokens.filter(t => t.type === 'size_px' || t.type === 'size_rem' || t.type === 'number');

  const colorLines = colors.map(t => {
    const name = toCamel(sanitizeName(t.key));
    const { r, g, b } = hexToArgbInts(t.resolved);
    return `    val ${name} = Color(red = ${r}, green = ${g}, blue = ${b})`;
  });

  const dimenLines = dims.map(t => {
    const name = toCamel(sanitizeName(t.key));
    if (t.type === 'size_px') {
      const v = parseFloat(t.resolved);
      return `    val ${name} = ${v}.dp`;
    }
    if (t.type === 'size_rem') {
      const rem = parseFloat(t.resolved);
      // 以 16px 為 1rem 的預設；對應到 sp，讓字級可縮放
      const sp = rem * 16;
      return `    val ${name} = ${sp}.sp`;
    }
    // number -> 無單位，保留成 Float
    return `    val ${name} = ${Number(t.resolved)}f`;
  });

  const file = `// Generated by Variables Compile Tool
package com.example.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object DesignTokens {
${colorLines.join('\n')}

${dimenLines.join('\n')}
}
`;
  return file;
};


