// 將已解析 tokens 產生 iOS UIKit (Swift) 檔案字串

const toCamel = (s) => s.replace(/[-_]+([a-zA-Z0-9])/g, (_, c) => (c || '').toUpperCase()).replace(/^([A-Z])/, (m) => m.toLowerCase());
const toPascal = (s) => {
  const camel = toCamel(s);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
};

const sanitizeName = (cssVarKey) => cssVarKey.replace(/^([a-zA-Z]+-)/, '').replace(/[^a-zA-Z0-9-_]/g, '');

const hexToRgb = (hex) => {
  let v = hex.replace('#', '').trim();
  if (v.length === 3) v = v.split('').map((c) => c + c).join('');
  const r = parseInt(v.substring(0, 2), 16) / 255;
  const g = parseInt(v.substring(2, 4), 16) / 255;
  const b = parseInt(v.substring(4, 6), 16) / 255;
  return { r, g, b };
};

export const generateIOSUIKit = ({ tokens }) => {
  if (!Array.isArray(tokens)) return '';

  const colors = tokens.filter(t => t.type === 'color');
  const dims = tokens.filter(t => t.type === 'size_px' || t.type === 'size_rem' || t.type === 'number');

  const colorLines = colors.map(t => {
    const name = toCamel(sanitizeName(t.key));
    const { r, g, b } = hexToRgb(t.resolved);
    return `    static let ${name} = UIColor(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)}, alpha: 1.0)`;
  });

  const dimenLines = dims.map(t => {
    const name = toCamel(sanitizeName(t.key));
    if (t.type === 'size_px') {
      const v = parseFloat(t.resolved);
      return `    static let ${name}: CGFloat = ${v}`;
    }
    if (t.type === 'size_rem') {
      const rem = parseFloat(t.resolved);
      // 以 16pt 為 1rem，輸出字體大小，UIKit 建議使用 CGFloat
      const pt = rem * 16;
      return `    static let ${name}: CGFloat = ${pt}`;
    }
    return `    static let ${name}: CGFloat = ${Number(t.resolved)}`;
  });

  const file = `// Generated by Variables Compile Tool
import UIKit

public enum DesignTokens { }

public extension DesignTokens {
  enum ColorSet {
${colorLines.join('\n')}
  }

  enum SizeSet {
${dimenLines.join('\n')}
  }
}
`;

  return file;
};


