// 將已解析 tokens 產生 iOS UIKit (Swift) 檔案字串

const toCamel = (s) => s.replace(/[-_]+([a-zA-Z0-9])/g, (_, c) => (c || '').toUpperCase()).replace(/^([A-Z])/, (m) => m.toLowerCase());
const toPascal = (s) => {
  const camel = toCamel(s);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
};

const sanitizeName = (cssVarKey) => cssVarKey.replace(/^([a-zA-Z]+-)/, '').replace(/[^a-zA-Z0-9-_]/g, '');

const hexToRgb = (hex) => {
  let v = hex.replace('#', '').trim();
  if (v.length === 3) v = v.split('').map((c) => c + c).join('');
  const r = parseInt(v.substring(0, 2), 16) / 255;
  const g = parseInt(v.substring(2, 4), 16) / 255;
  const b = parseInt(v.substring(4, 6), 16) / 255;
  return { r, g, b };
};

export const generateIOSUIKit = ({ tokens }) => {
  if (!Array.isArray(tokens)) return '';

  const colors = tokens.filter(t => t.type === 'color');
  const dims = tokens.filter(t => t.type === 'size_px' || t.type === 'size_rem' || t.type === 'number');

  const VAR_REF = /^var\((--[A-Za-z0-9-_]+)\)$/;
  const toName = (key) => toCamel(sanitizeName(key));

  const baseColors = colors.filter(t => !VAR_REF.test(t.raw));
  const aliasColors = colors.filter(t => VAR_REF.test(t.raw));

  const colorLines = [];
  baseColors.forEach(t => {
    const name = toName(t.key);
    const { r, g, b } = hexToRgb(t.resolved);
    colorLines.push(`    static let ${name} = UIColor(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)}, alpha: 1.0)`);
  });
  aliasColors.forEach(t => {
    const name = toName(t.key);
    const refKey = t.raw.match(VAR_REF)[1].replace(/^--/, '');
    const refName = toName(refKey);
    colorLines.push(`    static let ${name} = ${refName}`);
  });

  const baseDims = dims.filter(t => !VAR_REF.test(t.raw));
  const aliasDims = dims.filter(t => VAR_REF.test(t.raw));

  const dimenLines = [];
  baseDims.forEach(t => {
    const name = toName(t.key);
    if (t.type === 'size_px') {
      const v = parseFloat(t.resolved);
      dimenLines.push(`    static let ${name}: CGFloat = ${v}`);
    } else if (t.type === 'size_rem') {
      const rem = parseFloat(t.resolved);
      const pt = rem * 16;
      dimenLines.push(`    static let ${name}: CGFloat = ${pt}`);
    } else {
      dimenLines.push(`    static let ${name}: CGFloat = ${Number(t.resolved)}`);
    }
  });
  aliasDims.forEach(t => {
    const name = toName(t.key);
    const refKey = t.raw.match(VAR_REF)[1].replace(/^--/, '');
    const refName = toName(refKey);
    dimenLines.push(`    static let ${name} = ${refName}`);
  });

  const file = `// Generated by Variables Compile Tool
import UIKit

public enum DesignTokens { }

public extension DesignTokens {
  enum ColorSet {
${colorLines.join('\n')}
  }

  enum SizeSet {
${dimenLines.join('\n')}
  }
}
`;

  return file;
};


